# version: '3.8'

# services:
#   backend:
#     build: .
#     ports:
#       - "5000:5000"
#     environment:
#       - DATABASE_URL=postgresql://postgres:postgres@db:5432/urbantap
#       - JWT_SECRET=secret
#       - PORT=5000
#     depends_on:
#       - db
#     networks:
#       - urbantap-network
#     volumes:
#       - ./:/usr/src/app
#       - /usr/src/app/node_modules

#   db:
#     image: postgres:15
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=urbantap
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     networks:
#       - urbantap-network

# volumes:
#   postgres-data:

# networks:
#   urbantap-network:
#     driver: bridge


version: '3.8'

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/urbantap
      - JWT_SECRET=secret
      - PORT=5000
    depends_on:
      - db
    networks:
      - urbantap-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "npx prisma migrate deploy &&
             npm run start"

  db:
    container_name: db
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=urbantap
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - urbantap-network

volumes:
  postgres-data:

networks:
  urbantap-network:
    driver: bridge

